// =====================================================================
// GLOSSÁRIO — significado dos termos técnicos, na linguagem do mercado.
// Aparece SÓ no conteúdo das pílulas: o termo fica sublinhado e, ao ser
// tocado, abre a caixinha com o significado. Nunca em questões,
// alternativas ou explicações, para não entregar gabarito.
//
// Regra de escrita: uma frase que explique, uma segunda só se agregar o
// detalhe que a prova cobra. Sem circularidade ("benchmark é o benchmark
// do fundo") e sem jargão novo dentro da definição.
// =====================================================================
const GLOSSARIO = {
  // --- mercado, taxas e indicadores ---
  "benchmark": "Índice usado como referência para comparar o desempenho de um investimento. Se um fundo tem o CDI como benchmark, render menos que o CDI significa que ele ficou abaixo da própria referência.",
  "spread": "Diferença entre o que o banco paga a quem empresta dinheiro a ele e o que cobra de quem toma emprestado. É de onde sai boa parte do lucro da intermediação financeira.",
  "CDI": "Taxa dos empréstimos que os bancos fazem entre si, de um dia para o outro. Anda coladíssima na Selic e é a régua da renda fixa: 'rende 100% do CDI' quer dizer que acompanha essa taxa.",
  "Selic": "A taxa básica de juros da economia, definida pelo Copom a cada 45 dias. É o ponto de partida de todas as outras taxas do país.",
  "Selic Meta": "O alvo de juros anunciado pelo Copom. A taxa efetiva que o mercado pratica (a Selic Over) fica bem próxima dela, um pouco abaixo.",
  "Selic Over": "A taxa que de fato se pratica nas operações com títulos públicos de um dia. Costuma ficar 0,10 ponto percentual abaixo da Selic Meta.",
  "IPCA": "O índice oficial de inflação do Brasil, medido pelo IBGE. É a régua da meta de inflação e corrige os títulos públicos indexados a preços.",
  "IGP-M": "Índice de inflação calculado pela FGV, muito usado em contratos de aluguel. Sofre mais influência dos preços no atacado, por isso oscila mais que o IPCA.",
  "INPC": "Índice de inflação do IBGE voltado às famílias de renda mais baixa. Serve de referência para reajustes salariais.",
  "TR": "Taxa Referencial, um índice de correção que hoje rende muito pouco ou zero. Aparece na poupança e em financiamentos imobiliários.",
  "TLP": "Taxa de Longo Prazo, o custo dos financiamentos do BNDES. Substituiu a antiga TJLP e acompanha os juros de mercado dos títulos públicos.",
  "PTAX": "A taxa de câmbio oficial divulgada pelo Banco Central ao fim do dia. Serve de referência para contratos que dependem do dólar.",
  "PIB": "Soma de tudo que o país produz de bens e serviços num período. É o termômetro do tamanho e do crescimento da economia.",
  "taxa livre de risco": "O retorno que se consegue sem correr risco de calote, representado no Brasil pelos títulos do governo. Tudo que tem risco precisa render mais que ela para valer a pena.",
  "prêmio de risco": "O retorno a mais que um investimento precisa oferecer, acima da taxa livre de risco, para compensar o risco que ele carrega.",

  // --- renda fixa ---
  "renda fixa": "Investimento em que as regras de remuneração são conhecidas desde a aplicação: uma taxa fixa, um índice ou uma combinação dos dois. Você empresta dinheiro e sabe como o retorno será calculado.",
  "prefixado": "Título cuja taxa é definida na aplicação e não muda: você sabe exatamente quanto vai receber no vencimento, em reais.",
  "pós-fixado": "Título cujo rendimento acompanha um indicador, como a Selic ou o CDI. Você conhece a regra, mas só sabe o valor final no resgate.",
  "híbrido": "Título que combina uma taxa fixa com um índice, tipicamente 'IPCA mais 6% ao ano'. Protege da inflação e ainda entrega um ganho real.",
  "juro real": "O que sobra do rendimento depois de descontada a inflação. É o ganho que de fato aumenta o poder de compra.",
  "CDB": "Certificado de Depósito Bancário: você empresta dinheiro ao banco e recebe juros. Tem cobertura do FGC e paga imposto pela tabela regressiva.",
  "RDB": "Recibo de Depósito Bancário, parecido com o CDB, mas inegociável: não pode ser transferido nem vendido antes do prazo.",
  "LCI": "Letra de Crédito Imobiliário, emitida por bancos com lastro em crédito imobiliário. É isenta de imposto de renda para pessoa física e tem FGC.",
  "LCA": "Letra de Crédito do Agronegócio, mesma lógica da LCI, mas lastreada em crédito rural. Isenta de IR para pessoa física e coberta pelo FGC.",
  "LCD": "Letra de Crédito do Desenvolvimento, título bancário voltado a projetos de desenvolvimento, também isento de imposto de renda para pessoa física.",
  "CRI": "Certificado de Recebíveis Imobiliários: título emitido por securitizadora, lastreado em pagamentos futuros de imóveis. Isento de IR para PF e SEM cobertura do FGC.",
  "CRA": "Certificado de Recebíveis do Agronegócio, o equivalente do CRI para o agro. Isento de IR para pessoa física e sem FGC.",
  "LIG": "Letra Imobiliária Garantida, título bancário com dupla garantia: o banco emissor e uma carteira de créditos separada do patrimônio dele. Isenta de IR para PF.",
  "LF": "Letra Financeira, título de bancos para captar dinheiro de longo prazo. Tem valor mínimo alto e não conta com o FGC.",
  "debênture": "Título de dívida emitido por empresa não financeira para captar recursos. Quem compra vira credor da empresa, não sócio.",
  "debênture incentivada": "Debênture de projeto de infraestrutura que dá isenção de imposto de renda à pessoa física, como incentivo do governo ao setor.",
  "cupom": "Pagamento periódico de juros que alguns títulos fazem antes do vencimento, em vez de deixar tudo para o final.",
  "LTN": "Título público prefixado que não paga cupom: você compra com desconto e recebe R$ 1.000 no vencimento. No Tesouro Direto é o Tesouro Prefixado.",
  "NTN-B": "Título público que paga IPCA mais uma taxa fixa. No Tesouro Direto é o Tesouro IPCA+, o clássico para objetivos de longo prazo.",
  "NTN-F": "Título público prefixado que paga cupons semestrais de juros. No Tesouro Direto é o Tesouro Prefixado com Juros Semestrais.",
  "LFT": "Título público pós-fixado atrelado à Selic, o de menor oscilação de preço. No Tesouro Direto é o Tesouro Selic.",
  "duration": "O prazo médio em que o dinheiro do título efetivamente volta ao investidor, considerando todos os pagamentos. Quanto maior a duration, mais o preço balança quando os juros mudam.",
  "marcação a mercado": "Reavaliar todo dia quanto vale o título pelo preço que ele teria se fosse vendido hoje. É o que faz a cota oscilar mesmo em fundos de renda fixa.",
  "FGC": "Fundo Garantidor de Créditos: devolve até R$ 250 mil por CPF e por instituição, com teto global de R$ 1 milhão a cada 4 anos, se o banco quebrar.",

  // --- renda variável ---
  "renda variável": "Investimento sem retorno combinado: o resultado depende do desempenho do ativo e do humor do mercado. Ações são o exemplo típico.",
  "ação": "Menor pedaço do capital de uma empresa. Quem compra vira sócio e participa dos lucros e dos riscos do negócio.",
  "ordinária": "Ação que dá direito a voto nas assembleias. É a classe com poder de decisão sobre os rumos da companhia.",
  "preferencial": "Ação sem direito a voto, em regra, mas com preferência no recebimento de dividendos e no reembolso de capital.",
  "unit": "Pacote que junta ações de tipos diferentes num único papel negociado, geralmente uma ordinária mais preferenciais.",
  "dividendo": "Parte do lucro da empresa distribuída aos acionistas em dinheiro. Desde 2026 a isenção vale até R$ 50 mil por mês por empresa; acima disso há retenção de 10% sobre todo o valor recebido daquela companhia.",
  "JCP": "Juros sobre Capital Próprio: outra forma de a empresa remunerar o acionista. É despesa financeira para a companhia, que abate imposto, e sofre retenção na fonte de 17,5% para quem recebe, sem teto de isenção.",
  "bonificação": "Ações novas distribuídas de graça aos acionistas, a partir de reservas de lucro da empresa.",
  "subscrição": "Direito de comprar novas ações antes do mercado, num aumento de capital, para não ter sua participação diluída.",
  "bônus de subscrição": "Título que dá ao dono o direito de subscrever ações da empresa no futuro, por preço e prazo definidos.",
  "split": "Desdobramento: a empresa divide cada ação em várias, o que baixa o preço unitário e facilita a negociação. O valor total do investidor não muda.",
  "inplit": "Grupamento: várias ações viram uma só, elevando o preço unitário. Usado para tirar o papel da faixa de centavos.",
  "tag along": "Proteção do acionista minoritário: se o controle da empresa é vendido, ele tem o direito de vender as ações dele também, por no mínimo 80% do preço pago ao controlador.",
  "drag along": "O contrário do tag along: cláusula que obriga o minoritário a vender junto quando o controlador vende, para viabilizar a venda de 100% do negócio.",
  "free float": "A fatia das ações que circula livremente na bolsa, fora das mãos dos controladores. Quanto maior, melhor a liquidez do papel.",
  "IPO": "Oferta pública inicial: a primeira vez que uma empresa vende ações ao público e passa a ser negociada em bolsa.",
  "mercado primário": "Onde o papel é emitido pela primeira vez e o dinheiro vai para o caixa da empresa emissora.",
  "mercado secundário": "Onde os investidores negociam entre si papéis já emitidos. Dá liquidez ao mercado, mas não leva dinheiro novo à empresa.",
  "penny stock": "Ação negociada por centavos, tipicamente abaixo de R$ 1,00. Costuma ter pouca liquidez e risco alto.",
  "blue chip": "Ação de empresa grande, conhecida e muito negociada, com liquidez alta no dia a dia da bolsa.",
  "lote padrão": "Quantidade padronizada de negociação na bolsa, normalmente 100 ações. Abaixo disso a negociação é no mercado fracionário.",
  "home broker": "A plataforma pela internet em que o investidor envia ordens de compra e venda à corretora.",
  "day trade": "Comprar e vender o mesmo ativo no mesmo dia. Tem imposto de renda de 20% sobre o ganho, sem a isenção mensal do varejo.",
  "circuit breaker": "Interrupção automática dos negócios na bolsa quando o índice cai demais, para esfriar o mercado e conter o pânico.",

  // --- fundos ---
  "cota": "A menor fração do patrimônio de um fundo: quem investe compra cotas, e o valor de cada uma sobe ou desce com a carteira. Numa sociedade limitada, cota é a fração do capital que cabe a cada sócio.",
  "cotista": "O investidor dono de cotas do fundo. É ele quem assume os riscos e recebe os resultados da carteira.",
  "administrador": "Quem responde legalmente pelo fundo perante a CVM: contrata prestadores, cuida das informações e do cumprimento das regras.",
  "gestor": "Quem decide o que comprar e vender dentro da carteira do fundo, dentro da política de investimento definida.",
  "custodiante": "Quem guarda os ativos do fundo e mantém o registro de quem é o dono de cada papel.",
  "come-cotas": "Antecipação semestral do imposto de renda em alguns fundos, feita em maio e novembro pela alíquota menor da faixa. Em vez de dinheiro, o fisco leva cotas.",
  "chamada de capital": "Compromisso em que o investidor entra com o dinheiro aos poucos, conforme o fundo precisa investir. Comum em fundos de participações.",
  "taxa de administração": "Percentual anual sobre o patrimônio, cobrado para remunerar a gestão do fundo. Já está descontado na cota que você vê.",
  "taxa de performance": "Cobrança extra sobre o que o fundo render acima do benchmark. Só pode ser cobrada respeitando a linha d'água.",
  "linha d'água": "A regra que impede cobrar performance duas vezes sobre o mesmo ganho: o fundo precisa primeiro recuperar a queda anterior antes de voltar a cobrar.",
  "fundo aberto": "Fundo em que dá para aplicar e resgatar a qualquer momento, respeitando os prazos do regulamento.",
  "fundo fechado": "Fundo com número fixo de cotas e sem resgate: para sair antes do fim, o cotista vende suas cotas a outro investidor no mercado.",
  "FII": "Fundo de Investimento Imobiliário: aplica em imóveis ou em papéis do setor e distribui os rendimentos mensalmente, isentos de IR para PF que cumpra as condições legais.",
  "FIDC": "Fundo que compra direitos creditórios, ou seja, recebíveis de empresas, como duplicatas e parcelas de cartão.",
  "FIP": "Fundo de Investimento em Participações: compra participação em empresas, geralmente fechadas, para influenciar a gestão e vender depois com ganho.",
  "ETF": "Fundo de índice negociado em bolsa como se fosse uma ação, que replica a carteira de um índice de referência.",
  "gestão passiva": "Estratégia que busca apenas acompanhar o índice de referência, sem tentar superá-lo. Costuma ter custo menor.",
  "gestão ativa": "Estratégia em que o gestor escolhe os ativos tentando render mais que o benchmark, o que também eleva o custo e o risco.",
  "patrimônio líquido": "O que o fundo tem, menos o que ele deve. Dividido pelo número de cotas, dá o valor da cota.",

  // --- previdência e seguros ---
  "PGBL": "Plano de previdência que permite deduzir as contribuições até 12% da renda bruta tributável, para quem declara no modelo completo. Na saída, o IR incide sobre o valor total resgatado.",
  "VGBL": "Plano de previdência sem dedução na declaração, indicado para quem usa o modelo simplificado ou já atingiu o limite. Na saída, o IR incide só sobre o rendimento.",
  "tabela regressiva": "Regime de imposto em que a alíquota cai conforme o dinheiro fica mais tempo aplicado, chegando a 10% acima de dez anos na previdência.",
  "tabela progressiva": "Regime de imposto em que a alíquota cresce conforme o valor recebido, seguindo a mesma tabela do salário.",
  "portabilidade": "Transferir o saldo de um plano de previdência para outro, sem resgatar e sem pagar imposto na troca.",
  "carência": "Prazo mínimo que precisa ser cumprido antes de poder resgatar ou movimentar o dinheiro.",
  "renda vitalícia": "Forma de recebimento em que a seguradora paga uma renda mensal até o fim da vida do beneficiário.",
  "FIE": "Fundo em que o dinheiro dos planos de previdência é efetivamente investido. As taxas do plano são cobradas nele.",
  "sinistro": "O evento coberto pelo seguro quando ele de fato acontece: o roubo, o acidente, o incêndio.",
  "indenização": "O valor que a seguradora paga ao segurado quando o sinistro coberto ocorre.",
  "franquia": "A parte do prejuízo que fica por conta do segurado. A seguradora só paga o que passar desse valor.",
  "capitalização": "Produto que junta poupança programada e sorteios. Não é investimento: parte do dinheiro custeia os prêmios dos sorteios.",

  // --- crédito e serviços bancários ---
  "cheque especial": "Limite de crédito pré-aprovado na conta corrente, com juros altos, cobrados só sobre o valor e os dias efetivamente usados.",
  "rotativo": "O crédito que se forma quando o cliente não paga a fatura inteira do cartão. Tem os juros mais caros do mercado e duração limitada a um mês.",
  "CET": "Custo Efetivo Total: a taxa que reúne juros, tarifas, tributos e seguros de uma operação de crédito. É o número que permite comparar propostas de verdade.",
  "amortização": "A parte da parcela que efetivamente abate o valor devido. O resto da parcela é juros.",
  "SAC": "Sistema de Amortização Constante: a amortização é sempre igual e os juros vão caindo, então a prestação começa alta e diminui. Atenção: no atendimento ao cliente, a mesma sigla significa Serviço de Atendimento ao Consumidor.",
  "Price": "Sistema de amortização com prestações iguais do começo ao fim: no início paga-se mais juros e menos principal.",
  "leasing": "Arrendamento mercantil: a instituição compra o bem e aluga ao cliente, que pode ficar com ele ao fim do contrato pagando o valor residual.",
  "factoring": "Empresa que compra recebíveis de outras empresas com desconto. Não é instituição financeira e não pode captar dinheiro do público.",
  "penhor": "Empréstimo com garantia de um bem móvel entregue ao credor, como joias na Caixa Econômica Federal.",
  "alienação fiduciária": "Garantia em que o bem financiado fica em nome do credor até a quitação. É o que permite juros menores em veículos e imóveis.",
  "score": "Nota que estima a chance de um cliente pagar em dia, calculada por birôs de crédito a partir do histórico dele.",
  "rating": "Nota de risco de crédito atribuída por agências classificadoras a empresas, bancos e países. Quanto pior o rating, maior o juro exigido.",
  "SCR": "Sistema de Informações de Créditos do Banco Central, que reúne o endividamento dos clientes no sistema financeiro.",
  "conta de pagamento": "Conta oferecida por instituição de pagamento, para receber e movimentar dinheiro. Não tem FGC nem crédito direto como a conta corrente.",
  "adquirente": "A empresa que captura a transação do cartão no lojista e repassa o dinheiro a ele. A bandeira é quem define as regras da rede.",
  "custódia": "Serviço de guarda dos ativos do investidor, com registro de titularidade em nome dele.",
  "clearing": "Câmara que registra, compensa e liquida as operações, garantindo que quem comprou receba e quem vendeu seja pago.",
  "tesouraria": "A área do banco que administra o caixa e as posições próprias da instituição, casando o que entra e o que sai.",

  // --- sistema financeiro e regulação ---
  "CMN": "Conselho Monetário Nacional, o órgão máximo do sistema financeiro: define as regras, mas não executa nem fiscaliza.",
  "Copom": "Comitê do Banco Central que define a Selic a cada 45 dias, olhando a meta de inflação.",
  "CVM": "Autarquia que regula e fiscaliza o mercado de capitais: valores mobiliários, fundos, companhias abertas e quem distribui esses produtos.",
  "SUSEP": "Autarquia que fiscaliza seguros, previdência complementar aberta e capitalização.",
  "PREVIC": "Autarquia que fiscaliza os fundos de pensão, ou seja, a previdência complementar fechada.",
  "ANBIMA": "Associação do mercado que faz autorregulação e certificação. Cria códigos com regras adicionais às oficiais e aplica os exames como a CPA.",
  "B3": "A bolsa brasileira, onde se negociam ações, derivativos e outros ativos, com suas próprias câmaras de registro e liquidação.",
  "COAF": "Órgão que recebe e analisa as comunicações de operações suspeitas de lavagem de dinheiro.",
  "autorregulação": "Regras que o próprio mercado cria para si, acima do mínimo exigido pela lei. Vale para quem adere e é fiscalizada pela entidade, não pelo Estado.",
  "SPB": "Sistema de Pagamentos Brasileiro: o conjunto de regras e sistemas que fazem o dinheiro circular entre instituições com segurança.",
  "compulsório": "Parcela dos depósitos que os bancos são obrigados a deixar parada no Banco Central. Mexer nele aumenta ou reduz o dinheiro disponível para crédito.",
  "redesconto": "Empréstimo de curtíssimo prazo que o Banco Central faz aos bancos para socorrer a liquidez deles.",
  "open market": "Compra e venda de títulos públicos pelo Banco Central para regular a quantidade de dinheiro em circulação.",
  "política monetária": "O conjunto de instrumentos que o Banco Central usa para controlar a inflação, com destaque para a Selic.",
  "política fiscal": "As decisões do governo sobre arrecadar impostos e gastar. Afeta a dívida pública e, indiretamente, os juros.",
  "política cambial": "As ações que afetam a relação do real com as moedas estrangeiras e o fluxo de capitais.",
  "LRF": "Lei de Responsabilidade Fiscal: impõe limites de gasto e endividamento aos governos, especialmente com pessoal.",

  // --- conduta, ética e prevenção ---
  "suitability": "Dever de verificar se o produto é adequado ao perfil, aos objetivos e à situação financeira do cliente antes de recomendá-lo.",
  "API": "Análise do Perfil do Investidor: o questionário que classifica o cliente em conservador, moderado ou arrojado. Em tecnologia, a mesma sigla designa a conexão que faz dois sistemas conversarem, como no Open Finance.",
  "investidor qualificado": "Quem tem mais de R$ 1 milhão em investimentos e atesta essa condição por escrito, além de profissionais certificados quanto aos próprios recursos.",
  "investidor profissional": "Quem tem mais de R$ 10 milhões declarados, além de instituições financeiras, seguradoras, fundos e investidores não residentes. Todo profissional também é qualificado.",
  "chinese wall": "Separação obrigatória entre as áreas de uma instituição para que informações de uma não contaminem as decisões da outra, como gestão de recursos próprios e de terceiros.",
  "insider trading": "Usar informação privilegiada, ainda não pública, para ganhar dinheiro no mercado. É crime.",
  "front running": "Executar a ordem própria antes da ordem do cliente, para se aproveitar do efeito dela no preço. É crime.",
  "churning": "Girar a carteira do cliente sem necessidade só para gerar corretagem. Prática abusiva e vedada.",
  "conflito de interesses": "Situação em que o ganho do profissional ou da instituição pode se opor ao interesse do cliente. Resolve-se informando e priorizando o cliente.",
  "PLDFT": "Prevenção à Lavagem de Dinheiro e ao Financiamento do Terrorismo: o conjunto de deveres de conhecer o cliente, monitorar e comunicar suspeitas.",
  "KYC": "Conheça Seu Cliente: procedimentos de identificação e conhecimento do cliente, base de toda a prevenção à lavagem de dinheiro.",
  "lavagem de dinheiro": "Processo de dar aparência lícita a recursos de origem criminosa, em três fases: colocação, ocultação e integração.",
  "LGPD": "Lei Geral de Proteção de Dados: define como dados pessoais podem ser coletados e usados, exigindo base legal e finalidade clara.",
  "sigilo bancário": "Dever de não revelar informações financeiras do cliente, com quebra apenas nas hipóteses previstas em lei.",

  // --- finanças pessoais e análise ---
  "reserva de emergência": "Dinheiro guardado em aplicação de liquidez imediata e baixo risco, para cobrir imprevistos sem precisar resgatar investimentos de longo prazo.",
  "liquidez": "A facilidade de transformar um investimento em dinheiro sem perder valor. Poupança tem liquidez imediata; imóvel, quase nenhuma.",
  "volatilidade": "O tamanho do sobe e desce do preço de um ativo. Quanto maior, mais o valor oscila no caminho.",
  "diversificação": "Distribuir o dinheiro entre ativos diferentes para que o resultado não dependa de um só. Reduz o risco sem exigir abrir mão do retorno na mesma proporção.",
  "payback": "O tempo que um investimento leva para devolver o valor aplicado. Simples de calcular, mas ignora o que acontece depois e o valor do dinheiro no tempo.",
  "VPL": "Valor Presente Líquido: traz todos os fluxos futuros para hoje e desconta o investimento inicial. Positivo, o projeto cria valor.",
  "TIR": "Taxa Interna de Retorno: a taxa que zera o VPL do projeto. Serve para comparar com o custo do dinheiro.",
  "TMA": "Taxa Mínima de Atratividade: o retorno mínimo que o investidor exige para topar um projeto, dado o que ele conseguiria em outra aplicação.",
  "CMPC": "Custo Médio Ponderado de Capital, o WACC: quanto custa, na média, o dinheiro que a empresa usa, somando capital próprio e de terceiros conforme o peso de cada um.",
  "alavancagem": "Usar dinheiro de terceiros para ampliar o resultado. Multiplica o ganho quando dá certo e o prejuízo quando dá errado.",
  "custo de oportunidade": "O que você deixa de ganhar na melhor alternativa descartada ao escolher um caminho.",
  "orçamento": "O planejamento de quanto entra e quanto sai por período. É a base de qualquer plano financeiro pessoal.",
  "balanço patrimonial": "A fotografia do que a pessoa tem e do que ela deve num momento. A diferença é o patrimônio líquido dela.",

  // --- derivativos e câmbio ---
  "derivativo": "Contrato cujo valor deriva de outro ativo, como dólar, juros ou uma ação. Serve para proteger, arbitrar ou especular.",
  "ativo subjacente": "O ativo de referência do qual o derivativo tira o valor: o dólar de um contrato futuro de dólar, por exemplo.",
  "hedge": "Proteção: montar uma posição que compensa o prejuízo de outra se o mercado virar contra você.",
  "swap": "Contrato de troca de rentabilidades entre duas partes, como trocar uma taxa prefixada pela variação do dólar.",
  "cupom cambial": "O juro em dólar praticado no Brasil: quanto rende, em dólar, aplicar aqui dentro. Mostra o quanto o país paga para atrair capital externo.",
  "termo": "No mercado de derivativos, contrato de compra e venda com preço fixado hoje e liquidação numa data futura combinada. Cuidado: no dia a dia bancário, 'termo' também aparece no sentido comum de documento, como no termo de adesão de um fundo.",
  "opção": "Contrato que dá o direito, não a obrigação, de comprar ou vender um ativo por um preço determinado até certa data. Em outros contextos a palavra aparece no sentido comum de escolha, como na opção de compra ao fim de um leasing.",
  "prêmio": "No seguro, o valor que o segurado paga à seguradora pela proteção contratada — não confunda com a indenização, que é o que a seguradora paga quando ocorre o sinistro. Em investimentos, 'prêmio' também designa o retorno extra exigido por correr mais risco.",
  "COE": "Certificado de Operações Estruturadas: mistura renda fixa e variável num único produto, com cenários de retorno definidos. Pode ter capital protegido ou em risco.",

  // --- inovação, ESG e tecnologia ---
  "ESG": "Sigla de ambiental, social e governança: os três critérios usados para avaliar a sustentabilidade e a conduta de uma empresa, além do resultado financeiro.",
  "greenwashing": "Vender como sustentável algo que não é, maquiando o discurso ambiental sem prática que o sustente.",
  "blockchain": "Registro digital distribuído em que cada bloco de informação é encadeado ao anterior. Ninguém precisa confiar num intermediário para validar a informação.",
  "token": "Representação digital de um direito ou ativo dentro de uma rede blockchain.",
  "tokenização": "Transformar um ativo do mundo real, como um imóvel ou um recebível, em tokens negociáveis digitalmente.",
  "smart contract": "Programa que roda na blockchain e executa sozinho o que foi combinado, quando as condições acontecem.",
  "DeFi": "Finanças descentralizadas: serviços financeiros que funcionam por programas na blockchain, sem banco no meio.",
  "stablecoin": "Criptoativo que busca manter valor estável, geralmente atrelado ao dólar, para servir de meio de troca.",
  "CBDC": "Moeda digital emitida pelo próprio banco central de um país. No Brasil, o projeto é o Drex.",
  "Open Finance": "Sistema em que o cliente autoriza o compartilhamento dos próprios dados financeiros entre instituições. O dono do dado é o cliente.",
  "fintech": "Empresa que usa tecnologia para oferecer serviços financeiros, geralmente com estrutura mais enxuta que a dos bancos tradicionais.",
  "sandbox": "Ambiente controlado em que o regulador autoriza testar um produto inovador com público limitado e por prazo definido.",
  "criptoativo": "Ativo digital registrado em blockchain, sem emissor central garantindo valor. Não tem curso legal no Brasil.",
};
